version: '3'
services:
  passky-mysql:
    container_name: passky-mysql
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=passky
      - MYSQL_USER=passky
      - MYSQL_PASSWORD=uDWjSd8wB2HRBHei489o
    volumes: 
      - ./passky-mysql:/var/lib/mysql
    ports:
      - 3306:3306
  passky-php:
    container_name: passky-php
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: always
    volumes: 
      - ./passky-php:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      - passky-mysql
