version: '3'
services:
  passky-mysql:
    container_name: passky-mysql
    command: --default-authentication-plugin=mysql_native_password
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=passky
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - /passky:/var/lib/mysql
    networks:
      - passky
  passky-php:
    container_name: passky-php
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: always
    environment:
      # Database
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      # Mail
      - MAIL_HOST
      - MAIL_PORT
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - MAIL_USE_TLS
      # Account
      - ACCOUNT_MAX
      - ACCOUNT_MAX_PASSWORDS
      # Limiter
      - LIMITER_GET_PASSWORDS
      - LIMITER_SAVE_PASSWORD
      - LIMITER_EDIT_PASSWORD
      - LIMITER_DELETE_PASSWORD
      - LIMITER_CREATE_ACCOUNT
      - LIMITER_DELETE_ACCOUNT
      - LIMITER_IMPORT_PASSWORDS
      - LIMITER_FORGOT_USERNAME
    networks:
      - passky
    ports:
      - 8080:8080
    depends_on:
      - passky-mysql
networks:
  passky:
    driver: bridge
